import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;



import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Element;

import java.awt.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

public class Inventario extends javax.swing.JFrame {

    private articulosCRUD arcrud;
    
    public Inventario() {
        initComponents();
        arcrud = new articulosCRUD();
        llenarTabla();
    }
    
    private void llenarTabla(){
        ResultSet todos = arcrud.obtenerTodos();
        DefaultTableModel modeloT = (DefaultTableModel) jTable1.getModel();
        modeloT.setRowCount(0);
        
        try{
            while(todos.next()){
                modeloT.addRow(new Object[]{todos.getInt("id_articulo"),todos.getString("nombre"),todos.getString("c.nombre"),todos.getString("descripcion"),todos.getInt("existencia")});
            }
        }
        catch(SQLException x){
            System.out.println("Error al llenar la tabla"+x.getMessage());
        }
    }
    
    private void limpiarcampos(){
        txtNombre.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarNombre = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnTodos = new javax.swing.JButton();
        btnInventarioPDF = new javax.swing.JButton();
        btbReporteFecha = new javax.swing.JButton();
        btnReporteDepa = new javax.swing.JButton();
        MostrarBtn = new javax.swing.JButton();
        GraficaMostrada = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        usInventario = new javax.swing.JMenuItem();
        usAgregarSoli = new javax.swing.JMenuItem();
        txtCerrar = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario");

        lblBienvenido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("MERKS & SPENDS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblBienvenido))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Artículo", "Categoria", "Descripción", "Existencia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 700, 210));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscarNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnBuscarNombre.setText("Buscar por Nombre");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnTodos.setText("Mostrar Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        btnInventarioPDF.setText("Generar reporte inventario");
        btnInventarioPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioPDFActionPerformed(evt);
            }
        });

        btbReporteFecha.setText("Generar reporte por fechas");
        btbReporteFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbReporteFechaActionPerformed(evt);
            }
        });

        btnReporteDepa.setText("Generar reporte por departamentos");
        btnReporteDepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDepaActionPerformed(evt);
            }
        });

        MostrarBtn.setText("Mostrar gráfico");
        MostrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnInventarioPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btbReporteFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReporteDepa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscarNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarBtn)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTodos)
                    .addComponent(MostrarBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventarioPDF)
                    .addComponent(btbReporteFecha)
                    .addComponent(btnReporteDepa))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 690, 100));

        javax.swing.GroupLayout GraficaMostradaLayout = new javax.swing.GroupLayout(GraficaMostrada);
        GraficaMostrada.setLayout(GraficaMostradaLayout);
        GraficaMostradaLayout.setHorizontalGroup(
            GraficaMostradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        GraficaMostradaLayout.setVerticalGroup(
            GraficaMostradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jPanel1.add(GraficaMostrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jMenu2.setText("Menú");

        usInventario.setText("Inventario");
        usInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usInventarioActionPerformed(evt);
            }
        });
        jMenu2.add(usInventario);

        usAgregarSoli.setText("Agregar solicitud");
        usAgregarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usAgregarSoliActionPerformed(evt);
            }
        });
        jMenu2.add(usAgregarSoli);

        txtCerrar.setText("Cerrar sesión");
        txtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCerrarActionPerformed(evt);
            }
        });
        jMenu2.add(txtCerrar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        //1. obtener el valor del txt
        String nombretext = txtNombre.getText();

        //2.Validar txt vacio
        if(nombretext.isEmpty()){
            JOptionPane.showMessageDialog(this,"El campo es obligatorio","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        //3. Busqueda, llenado de la tabla
        try{
            ResultSet rs = arcrud.bucarporNombre(nombretext);
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            if(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("id_articulo"),rs.getString("nombre"),rs.getString("c.nombre"),rs.getString("descripcion"),rs.getInt("existencia")});
                

            }else {
                JOptionPane.showMessageDialog(this, "No se encontró un articulo con ese nombre", "Error", JOptionPane.WARNING_MESSAGE);

            }
        }
        catch(SQLException e){
            System.out.println("Error al llenar la tabla: "+e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        llenarTabla();
        limpiarcampos();
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnInventarioPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioPDFActionPerformed
        Document documento = new Document();
        
        try{
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/OneDrive/Escritorio/Reporte_Inventario.pdf"));
            documento.open();
            
            Paragraph titulo = new Paragraph("REPORTE DE INVENTARIO", FontFactory.getFont("Arial", 20, Font.BOLD));
            titulo.setAlignment(Element.ALIGN_CENTER);
            documento.add(titulo);
            documento.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("ID");
            tabla.addCell("Nombre");
            tabla.addCell("Categoria");
            tabla.addCell("Descripcion");
            tabla.addCell("Existencia");
            
            ResultSet rs = arcrud.reporteInventario();
            if(rs.next()){
                do{
                    tabla.addCell(rs.getString(1));
                    tabla.addCell(rs.getString(2));
                    tabla.addCell(rs.getString(3));
                    tabla.addCell(rs.getString(4));
                    tabla.addCell(rs.getString(5));
                }while(rs.next());
                documento.add(tabla);
            }
            documento.close(); // <- dentro del try
            JOptionPane.showMessageDialog(this, "Reporte creado");
        }catch(DocumentException | FileNotFoundException | SQLException e){
             System.out.println( "Error al generar PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnInventarioPDFActionPerformed

    private void usInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usInventarioActionPerformed
        Inventario IN = new  Inventario();
        IN.setVisible(true);
    }//GEN-LAST:event_usInventarioActionPerformed

    private void usAgregarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usAgregarSoliActionPerformed
        Agregar_uSolicitud AS = new  Agregar_uSolicitud();
        AS.setVisible(true);
    }//GEN-LAST:event_usAgregarSoliActionPerformed

    private void btbReporteFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbReporteFechaActionPerformed
        Document documento = new Document();
        
        try{
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/OneDrive/Escritorio/Reporte_pedidos_fechas.pdf"));
            documento.open();
            
            Paragraph titulo = new Paragraph("PEDIDOS POR FECHAS", FontFactory.getFont("Arial", 20, Font.BOLD));
            titulo.setAlignment(Element.ALIGN_CENTER);
            documento.add(titulo);
            documento.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(2);
            tabla.addCell("Fecha");
            tabla.addCell("Número pedidos");
            
            ResultSet rs = arcrud.reporteFechas();
            if(rs.next()){
                do{
                    tabla.addCell(rs.getString(1));
                    tabla.addCell(rs.getString(2));
                }while(rs.next());
                documento.add(tabla);
            }
            documento.close(); // <- dentro del try
            JOptionPane.showMessageDialog(this, "Reporte creado");
        }catch(DocumentException | FileNotFoundException | SQLException e){
             System.out.println( "Error al generar PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btbReporteFechaActionPerformed

    private void btnReporteDepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDepaActionPerformed
        Document documento = new Document();
        
        try{
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/OneDrive/Escritorio/Reporte_departamentos.pdf"));
            documento.open();
            
            Paragraph titulo = new Paragraph("PEDIDOS POR DEPARTAMENTOS", FontFactory.getFont("Arial", 20, Font.BOLD));
            titulo.setAlignment(Element.ALIGN_CENTER);
            documento.add(titulo);
            documento.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(7);
            tabla.addCell("ID solicitud");
            tabla.addCell("Usuario");
            tabla.addCell("Departamento");
            tabla.addCell("Cantidad");
            tabla.addCell("Fecha");
            tabla.addCell("Hora");
            tabla.addCell("Estado");
            
            ResultSet rs = arcrud.reporteDepartamentos();
            if(rs.next()){
                do{
                    tabla.addCell(rs.getString(1));
                    tabla.addCell(rs.getString(2));
                    tabla.addCell(rs.getString(3));
                    tabla.addCell(rs.getString(4));
                    tabla.addCell(rs.getString(5));
                    tabla.addCell(rs.getString(6));
                    tabla.addCell(rs.getString(7));
                }while(rs.next());
                documento.add(tabla);
            }
            documento.close(); // <- dentro del try
            JOptionPane.showMessageDialog(this, "Reporte creado");
        }catch(DocumentException | FileNotFoundException | SQLException e){
             System.out.println( "Error al generar PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnReporteDepaActionPerformed

    private void MostrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBtnActionPerformed
        System.out.println("Botón presionado - Conectando a BD...");

        try {
            // 1. Obtener datos REALES desde MySQL
            DefaultCategoryDataset dataset = arcrud.obtenerDatosReales();

            // 2. Crear el gráfico con los datos reales
            JFreeChart chart = ChartFactory.createBarChart(
                "Artículos más vendidos en MERKS & SPEN",
                "Artículos",
                "Cantidad vendida",
                dataset
            );

            // 3. Configurar el panel del gráfico
            ChartPanel chartPanel = new ChartPanel(chart) {
                @Override
                public Dimension getPreferredSize() {
                    return new Dimension(GraficaMostrada.getWidth(), GraficaMostrada.getHeight());
                }
            };

            // 4. Mostrar en el panel
            GraficaMostrada.removeAll();
            GraficaMostrada.setLayout(new BorderLayout());
            GraficaMostrada.add(chartPanel, BorderLayout.CENTER);
            GraficaMostrada.revalidate();
            GraficaMostrada.repaint();

            System.out.println("Gráfico generado con datos reales!");

        } catch (SQLException e) {
            System.err.println("Error de BD: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error al conectar con la BD: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            System.err.println("Error inesperado: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                "Error al generar gráfico: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MostrarBtnActionPerformed

    private void txtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCerrarActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Deseas cerrar sesión?", "Cerrar Sesión",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            InicioSesion IS = new InicioSesion();
            IS.setVisible(true);
            this.setVisible(false);
            InicioSesion.id_usuario = 0;
            InicioSesion.nombre_usuario = null;
            InicioSesion.privilegio = 0;
            InicioSesion.id_departamento = 0;
        }
    }//GEN-LAST:event_txtCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraficaMostrada;
    private javax.swing.JButton MostrarBtn;
    private javax.swing.JButton btbReporteFecha;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnInventarioPDF;
    private javax.swing.JButton btnReporteDepa;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JMenuItem txtCerrar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JMenuItem usAgregarSoli;
    private javax.swing.JMenuItem usInventario;
    // End of variables declaration//GEN-END:variables
}
